Repository Project-FleX-PFX/Licentra, pull requests merged in 2025-05, with the labels that each got.

#33 fix(admin license activate,SCRUM-133): fix critical bug
  backend/services/license_service.rb
Labels: bug

#36 feat(SCRUM-133-135): Added Log Export and Lock by Admin
  backend/dao/security_log_dao.rb
  backend/dao/user_dao.rb
  backend/routes/history_routes.rb
  backend/services/user_service.rb
  frontend/views/history/index.erb
Labels: enhancement

#38 feat(password,SCRUM-178): implemented thread
  backend/routes/auth_routes.rb
Labels: Security

#40 feat(login,SCRUM-181):changed login message to constant
  backend/services/auth_service.rb
Labels: Security
